"""Offline training script for SIBI and BISINDO gesture classifiers.

Expects a CSV generated by scripts/extract_landmarks.py.
Features are already wrist-normalized — do NOT normalize again here.

CSV format (output of extract_landmarks.py):
  - 126 feature columns named f0..f125: 2 hands x 21 landmarks x (x, y, z)
    Already normalized relative to each hand's wrist.
    Second hand columns are 0.0 for single-hand signs.
  - 1 label column: the gesture class name

Usage:
  python scripts/train_model.py --mode sibi --dataset data/sibi_landmarks.csv
  python scripts/train_model.py --mode bisindo --dataset data/bisindo_landmarks.csv
"""

import argparse
from pathlib import Path

import joblib
import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

MODEL_DIR = Path(__file__).parent.parent / "app" / "ai" / "models"
MODEL_DIR.mkdir(parents=True, exist_ok=True)

def load_features(df: pd.DataFrame) -> np.ndarray:
    """Extract the feature matrix from the CSV.

    Landmarks are already wrist-normalized by extract_landmarks.py.
    No further normalization is applied here.

    Args:
        df: DataFrame with 126 feature columns (f0..f125) and a 'label' column.

    Returns:
        Float32 array of shape (n_samples, 126).
    """
    feature_cols = [c for c in df.columns if c != "label"]
    return df[feature_cols].values.astype(np.float32)


def train(mode: str, dataset_path: str) -> None:
    print(f"\n{'='*40}")
    print(f"Training {mode.upper()} model")
    print(f"Dataset : {dataset_path}")

    df = pd.read_csv(dataset_path)
    print(f"Samples : {len(df)}")
    print(f"Labels  : {df['label'].nunique()} classes")
    print(f"Classes : {sorted(df['label'].unique())}")

    X = load_features(df)
    y = df["label"].values

    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42, stratify=y
    )

    clf = RandomForestClassifier(
        n_estimators=200,
        max_depth=None,
        random_state=42,
        n_jobs=-1,
    )
    print("\nTraining...")
    clf.fit(X_train, y_train)

    print("\nEvaluation on held-out test set:")
    y_pred = clf.predict(X_test)
    print(classification_report(y_test, y_pred))

    output_path = MODEL_DIR / f"{mode}_model.joblib"
    joblib.dump(clf, output_path)
    print(f"[OK] Model saved: {output_path}")


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Train a gesture classifier for Sapa Isyarat."
    )
    parser.add_argument(
        "--mode",
        choices=["sibi", "bisindo"],
        required=True,
        help="Which sign language model to train.",
    )
    parser.add_argument(
        "--dataset",
        required=True,
        help="Path to the CSV dataset file.",
    )
    args = parser.parse_args()
    train(args.mode, args.dataset)


if __name__ == "__main__":
    main()
